import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Futureflx",
  description: "Generated by create next app",
};

export type ChildrenType = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en" data-theme="light">
      <header>
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
      </header>
      <body className="bg-gray-200">{children}</body>
    </html>
  );
};

export default RootLayout;
